export const BOOT_STATE = 'BOOT_STATE';
export const LOAD_STATE = 'LOAD_STATE';
export const HUB_STATE = 'HUB_STATE';
export const EARTH_WORLD_STATE = 'EARTH_WORLD_STATE';
export const MOLTEN_WORLD_STATE = 'MOLTEN_WORLD_STATE';
export const FROZEN_WORLD_STATE = 'FROZEN_WORLD_STATE';
export const JUNGLE_WORLD_STATE = 'JUNGLE_WORLD_STATE';
